name: collegram
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - jupyter_server
  - matplotlib
  - numpy
  - scipy
  - polars
  - pip:
    # local package
    - -e .
    # For faster media DL:
    - cryptg
    - python-dotenv
    - tqdm
    - lingua-language-detector
    - pre-commit
    - git+https://github.com/TLouf/plots.git
