name: collegram
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - jupyter_server
  - matplotlib
  - numpy
  - polars
  - pip:
    # local package
    - -e .[scripts,media]
    - pre-commit
    - git+https://github.com/TLouf/plots.git
